language: python

os:
    - linux


sudo: false

python:
    - 2.7
    - 3.5
    - 3.6
    
install:
  - pip install -r requirements.txt
  - pip3 install -r requirements.txt
# command to run tests    


script:
  - pytest  # or py.test for Python versions 3.5 and below
